import slugify from "slugify";
import Story from "../../Models/Story";

/*
@params title: Story title
@params content: Story content markdown.
@param author: Story author id

slug is autogenerated by title
*/
const createStory = async (req, res) => {
  const { title, content, imageUrl, tags } = req.body;
  const author = req.user.id;
  const slug = title && slugify(title);

  try {
    const storyPresent = await Story.findOne({ slug });
    if (storyPresent) {
      throw { name: "Duplicate title" };
    }
    const story = await Story.create({
      title,
      content,
      author,
      slug,
      imageUrl,
      tags,
    });
    return res.status(200).send(story);
  } catch (err) {
    console.log("**story req err **\n", err);

    if (err.name === "Duplicate title") {
      return res.status(400).json({ error: "Bad request", reference: err });
    } else return res.status(500).send({ error: "Internal Server error" });
  }
};
export default createStory;
